### ISSUE TITLE
Height auto increased on responsive design

### ISSUE THREAD

**Issue by webtuts4u** [jnicol/particleground#12]
Hi

I am receiving this when i am changing the viewport. On large display (width 1170px) is working good. When i am seen my design on different width such as 768px, 991px, 1024px the height of particales wrapper auto increased.

Hope you have any solution for this.

**Comment by jnicol** [comment]
Can you put up a demo I can look at?

**Comment by webtuts4u** [comment]
http://1neclick.biz/test/particleground/

Check this testing demo. On responsive test in mozilla firefox browser height is auto increased every time when i change the viewport. 

Please test with the browser responsive test tool.
(Ctrl+Shift+M) in mozilla firefox.

hope this demo is sufficient to explain the issue.

**Comment by jnicol** [comment]
Giving the canvas element display:block fixed it. I thought canvas was a block level element but I guess not. This is fixed in 321dcb528b06e0ce99ee0ba4c2d5d21345f093fa
